In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks.
Matplatlib merupakan library python untuk presentasi data berupa grafik atau plot

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[['Australia' 46.0 72000.0]
 ['Indonesia' 26.0 48000.0]
 ['Malaysia' 32.0 54000.0]
 ['Indonesia' 36.0 61000.0]
 ['Malaysia' 41.0 nan]
 ['Australia' 37.0 58000.0]
 ['Indonesia' nan 52000.0]
 ['Australia' 47.0 79000.0]
 ['Malaysia' 52.0 83000.0]
 ['Australia' 38.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] =imputer.transform(x[:,1:3])

In [7]:
print(x)

[['Australia' 46.0 72000.0]
 ['Indonesia' 26.0 48000.0]
 ['Malaysia' 32.0 54000.0]
 ['Indonesia' 36.0 61000.0]
 ['Malaysia' 41.0 63777.77777777778]
 ['Australia' 37.0 58000.0]
 ['Indonesia' 39.44444444444444 52000.0]
 ['Australia' 47.0 79000.0]
 ['Malaysia' 52.0 83000.0]
 ['Australia' 38.0 67000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 46.0 72000.0]
 [0.0 1.0 0.0 26.0 48000.0]
 [0.0 0.0 1.0 32.0 54000.0]
 [0.0 1.0 0.0 36.0 61000.0]
 [0.0 0.0 1.0 41.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 58000.0]
 [0.0 1.0 0.0 39.44444444444444 52000.0]
 [1.0 0.0 0.0 47.0 79000.0]
 [0.0 0.0 1.0 52.0 83000.0]
 [1.0 0.0 0.0 38.0 67000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[0.0 1.0 0.0 39.44444444444444 52000.0]
 [0.0 0.0 1.0 41.0 63777.77777777778]
 [1.0 0.0 0.0 46.0 72000.0]
 [0.0 1.0 0.0 36.0 61000.0]
 [0.0 1.0 0.0 26.0 48000.0]
 [1.0 0.0 0.0 47.0 79000.0]
 [0.0 0.0 1.0 52.0 83000.0]
 [1.0 0.0 0.0 37.0 58000.0]]


In [14]:
print(x_test)

[[0.0 0.0 1.0 32.0 54000.0]
 [1.0 0.0 0.0 38.0 67000.0]]


In [15]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [18]:
print(x_train)

[[0.0 1.0 0.0 -0.1483395462120736 -1.0781259408412425]
 [0.0 0.0 1.0 0.05933581848482906 -0.07013167641635372]
 [1.0 0.0 0.0 0.7268637764391583 0.633562432710455]
 [0.0 1.0 0.0 -0.6081921394695002 -0.30786617274297867]
 [0.0 1.0 0.0 -1.9432480553781586 -1.420463615551582]
 [1.0 0.0 0.0 0.8603693680300242 1.232653363453549]
 [0.0 0.0 1.0 1.5278973259843533 1.5749910381638885]
 [1.0 0.0 0.0 -0.47468654787863435 -0.5646194287757332]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 -1.1422145058329636 -0.9069571034860727]
 [1.0 0.0 0.0 -0.3411809562877685 0.2056403393225306]]
